apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api-conversao
spec:
  replicas: 10
  selector: 
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels: 
        app: api-conversao
    spec:
      containers: 
        - name: api-conversao
          image: thiagokramer/api-conversao:latest
          ports:
            - containerPort: 80

--- 

apiVersion: v1
kind: Service
metadata: 
  name: api-conversao-service
spec: 
  selector: 
    app: api-conversao
  ports:
    - port: 80
      nodePort: 30000
  type: NodePort